export const BAN_LIST_REQUESTED = 'BAN/BAN_LIST_REQUESTED'
export const BAN_LIST_SUCCEEDED = 'BAN/BAN_LIST_SUCCEEDED'
export const BAN_LIST_FAILED = 'BAN/BAN_LIST_FAILED'
export const BAN_LIST_REMOVE = 'BAN/BAN_LIST_REMOVE'

export const REMOVE_BAN_REQUESTED = 'BAN/REMOVE_BAN_REQUESTED'
export const REMOVE_BAN_SUCCEED = 'BAN/REMOVE_BAN_SUCCEED'
export const REMOVE_BAN_FAILED = 'BAN/REMOVE_BAN_FAILED'
